//
// Autogenerated by Thrift Compiler (0.18.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

const thrift = require('thrift');
const Thrift = thrift.Thrift;
const Int64 = require('node-int64');

const services_ttypes = require('./services_types');
const uuid_ttypes = require('./uuid_types');
const communication_ttypes = require('./communication_types');


const Service = require('./Service');
const ServiceClient = Service.Client;
const ServiceProcessor = Service.Processor;
const ttypes = require('./learn_types');
//HELPER FUNCTIONS AND STRUCTURES

const ActiveLearnerClientService_submitSort_args = class {
  constructor(args) {
    this.sessionId = null;
    this.unitIds = null;
    if (args) {
      if (args.sessionId !== undefined && args.sessionId !== null) {
        this.sessionId = new uuid_ttypes.UUID(args.sessionId);
      }
      if (args.unitIds !== undefined && args.unitIds !== null) {
        this.unitIds = Thrift.copyList(args.unitIds, [services_ttypes.AnnotationUnitIdentifier]);
      }
    }
  }

  read (input) {
    input.readStructBegin();
    while (true) {
      const ret = input.readFieldBegin();
      const ftype = ret.ftype;
      const fid = ret.fid;
      if (ftype == Thrift.Type.STOP) {
        break;
      }
      switch (fid) {
        case 1:
        if (ftype == Thrift.Type.STRUCT) {
          this.sessionId = new uuid_ttypes.UUID();
          this.sessionId.read(input);
        } else {
          input.skip(ftype);
        }
        break;
        case 2:
        if (ftype == Thrift.Type.LIST) {
          this.unitIds = [];
          const _rtmp311 = input.readListBegin();
          const _size10 = _rtmp311.size || 0;
          for (let _i12 = 0; _i12 < _size10; ++_i12) {
            let elem13 = null;
            elem13 = new services_ttypes.AnnotationUnitIdentifier();
            elem13.read(input);
            this.unitIds.push(elem13);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        default:
          input.skip(ftype);
      }
      input.readFieldEnd();
    }
    input.readStructEnd();
    return;
  }

  write (output) {
    output.writeStructBegin('ActiveLearnerClientService_submitSort_args');
    if (this.sessionId !== null && this.sessionId !== undefined) {
      output.writeFieldBegin('sessionId', Thrift.Type.STRUCT, 1);
      this.sessionId.write(output);
      output.writeFieldEnd();
    }
    if (this.unitIds !== null && this.unitIds !== undefined) {
      output.writeFieldBegin('unitIds', Thrift.Type.LIST, 2);
      output.writeListBegin(Thrift.Type.STRUCT, this.unitIds.length);
      for (let iter14 in this.unitIds) {
        if (this.unitIds.hasOwnProperty(iter14)) {
          iter14 = this.unitIds[iter14];
          iter14.write(output);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    output.writeFieldStop();
    output.writeStructEnd();
    return;
  }

};
const ActiveLearnerClientService_submitSort_result = class {
  constructor(args) {
  }

  read (input) {
    input.readStructBegin();
    while (true) {
      const ret = input.readFieldBegin();
      const ftype = ret.ftype;
      if (ftype == Thrift.Type.STOP) {
        break;
      }
      input.skip(ftype);
      input.readFieldEnd();
    }
    input.readStructEnd();
    return;
  }

  write (output) {
    output.writeStructBegin('ActiveLearnerClientService_submitSort_result');
    output.writeFieldStop();
    output.writeStructEnd();
    return;
  }

};
const ActiveLearnerClientServiceClient = exports.Client = class ActiveLearnerClientServiceClient extends ServiceClient {
  constructor(output, pClass) {
    super(output, pClass);
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
  }
  seqid () { return this._seqid; }
  new_seqid () { return this._seqid += 1; }

  submitSort (sessionId, unitIds) {
    this._seqid = this.new_seqid();
    const self = this;
    return new Promise((resolve, reject) => {
      self._reqs[self.seqid()] = (error, result) => {
        return error ? reject(error) : resolve(result);
      };
      self.send_submitSort(sessionId, unitIds);
    });
  }

  send_submitSort (sessionId, unitIds) {
    const output = new this.pClass(this.output);
    const params = {
      sessionId: sessionId,
      unitIds: unitIds
    };
    const args = new ActiveLearnerClientService_submitSort_args(params);
    try {
      output.writeMessageBegin('submitSort', Thrift.MessageType.CALL, this.seqid());
      args.write(output);
      output.writeMessageEnd();
      return this.output.flush();
    }
    catch (e) {
      delete this._reqs[this.seqid()];
      if (typeof output.reset === 'function') {
        output.reset();
      }
      throw e;
    }
  }

  recv_submitSort (input, mtype, rseqid) {
    const callback = this._reqs[rseqid] || function() {};
    delete this._reqs[rseqid];
    if (mtype == Thrift.MessageType.EXCEPTION) {
      const x = new Thrift.TApplicationException();
      x.read(input);
      input.readMessageEnd();
      return callback(x);
    }
    const result = new ActiveLearnerClientService_submitSort_result();
    result.read(input);
    input.readMessageEnd();

    callback(null);
  }
};
const ActiveLearnerClientServiceProcessor = exports.Processor = class ActiveLearnerClientServiceProcessor extends ServiceProcessor {
  constructor(handler) {
    super(handler);
    this._handler = handler;
  }
  process (input, output) {
    const r = input.readMessageBegin();
    if (this['process_' + r.fname]) {
      return this['process_' + r.fname].call(this, r.rseqid, input, output);
    } else {
      input.skip(Thrift.Type.STRUCT);
      input.readMessageEnd();
      const x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
      output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
      x.write(output);
      output.writeMessageEnd();
      output.flush();
    }
  }
  process_submitSort (seqid, input, output) {
    const args = new ActiveLearnerClientService_submitSort_args();
    args.read(input);
    input.readMessageEnd();
    if (this._handler.submitSort.length === 2) {
      new Promise((resolve) => resolve(this._handler.submitSort.bind(this._handler)(
        args.sessionId,
        args.unitIds
      ))).then(result => {
        const result_obj = new ActiveLearnerClientService_submitSort_result({success: result});
        output.writeMessageBegin("submitSort", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }).catch(err => {
        let result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("submitSort", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
    } else {
      this._handler.submitSort(args.sessionId, args.unitIds, (err, result) => {
        let result_obj;
        if ((err === null || typeof err === 'undefined')) {
          result_obj = new ActiveLearnerClientService_submitSort_result((err !== null || typeof err === 'undefined') ? err : {success: result});
          output.writeMessageBegin("submitSort", Thrift.MessageType.REPLY, seqid);
        } else {
          result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
          output.writeMessageBegin("submitSort", Thrift.MessageType.EXCEPTION, seqid);
        }
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      });
    }
  }
};
