//
// Autogenerated by Thrift Compiler (0.18.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

const thrift = require('thrift');
const Thrift = thrift.Thrift;
const Int64 = require('node-int64');

const context_ttypes = require('./context_types');
const metadata_ttypes = require('./metadata_types');
const language_ttypes = require('./language_types');
const structure_ttypes = require('./structure_types');
const entities_ttypes = require('./entities_types');
const situations_ttypes = require('./situations_types');
const ex_ttypes = require('./ex_types');
const email_ttypes = require('./email_types');
const twitter_ttypes = require('./twitter_types');
const audio_ttypes = require('./audio_types');
const communication_ttypes = require('./communication_types');
const services_ttypes = require('./services_types');


const ttypes = module.exports = {};
