//
// Autogenerated by Thrift Compiler (0.18.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

const thrift = require('thrift');
const Thrift = thrift.Thrift;
const Int64 = require('node-int64');


const ttypes = module.exports = {};
const NITFInfo = module.exports.NITFInfo = class {
  constructor(args) {
    this.alternateURL = null;
    this.articleAbstract = null;
    this.authorBiography = null;
    this.banner = null;
    this.biographicalCategoryList = null;
    this.columnName = null;
    this.columnNumber = null;
    this.correctionDate = null;
    this.correctionText = null;
    this.credit = null;
    this.dayOfWeek = null;
    this.descriptorList = null;
    this.featurePage = null;
    this.generalOnlineDescriptorList = null;
    this.guid = null;
    this.kicker = null;
    this.leadParagraphList = null;
    this.locationList = null;
    this.nameList = null;
    this.newsDesk = null;
    this.normalizedByline = null;
    this.onlineDescriptorList = null;
    this.onlineHeadline = null;
    this.onlineLeadParagraph = null;
    this.onlineLocationList = null;
    this.onlineOrganizationList = null;
    this.onlinePeople = null;
    this.onlineSectionList = null;
    this.onlineTitleList = null;
    this.organizationList = null;
    this.page = null;
    this.peopleList = null;
    this.publicationDate = null;
    this.publicationDayOfMonth = null;
    this.publicationMonth = null;
    this.publicationYear = null;
    this.section = null;
    this.seriesName = null;
    this.slug = null;
    this.taxonomicClassifierList = null;
    this.titleList = null;
    this.typesOfMaterialList = null;
    this.url = null;
    this.wordCount = null;
    if (args) {
      if (args.alternateURL !== undefined && args.alternateURL !== null) {
        this.alternateURL = args.alternateURL;
      }
      if (args.articleAbstract !== undefined && args.articleAbstract !== null) {
        this.articleAbstract = args.articleAbstract;
      }
      if (args.authorBiography !== undefined && args.authorBiography !== null) {
        this.authorBiography = args.authorBiography;
      }
      if (args.banner !== undefined && args.banner !== null) {
        this.banner = args.banner;
      }
      if (args.biographicalCategoryList !== undefined && args.biographicalCategoryList !== null) {
        this.biographicalCategoryList = Thrift.copyList(args.biographicalCategoryList, [null]);
      }
      if (args.columnName !== undefined && args.columnName !== null) {
        this.columnName = args.columnName;
      }
      if (args.columnNumber !== undefined && args.columnNumber !== null) {
        this.columnNumber = args.columnNumber;
      }
      if (args.correctionDate !== undefined && args.correctionDate !== null) {
        this.correctionDate = args.correctionDate;
      }
      if (args.correctionText !== undefined && args.correctionText !== null) {
        this.correctionText = args.correctionText;
      }
      if (args.credit !== undefined && args.credit !== null) {
        this.credit = args.credit;
      }
      if (args.dayOfWeek !== undefined && args.dayOfWeek !== null) {
        this.dayOfWeek = args.dayOfWeek;
      }
      if (args.descriptorList !== undefined && args.descriptorList !== null) {
        this.descriptorList = Thrift.copyList(args.descriptorList, [null]);
      }
      if (args.featurePage !== undefined && args.featurePage !== null) {
        this.featurePage = args.featurePage;
      }
      if (args.generalOnlineDescriptorList !== undefined && args.generalOnlineDescriptorList !== null) {
        this.generalOnlineDescriptorList = Thrift.copyList(args.generalOnlineDescriptorList, [null]);
      }
      if (args.guid !== undefined && args.guid !== null) {
        this.guid = args.guid;
      }
      if (args.kicker !== undefined && args.kicker !== null) {
        this.kicker = args.kicker;
      }
      if (args.leadParagraphList !== undefined && args.leadParagraphList !== null) {
        this.leadParagraphList = Thrift.copyList(args.leadParagraphList, [null]);
      }
      if (args.locationList !== undefined && args.locationList !== null) {
        this.locationList = Thrift.copyList(args.locationList, [null]);
      }
      if (args.nameList !== undefined && args.nameList !== null) {
        this.nameList = Thrift.copyList(args.nameList, [null]);
      }
      if (args.newsDesk !== undefined && args.newsDesk !== null) {
        this.newsDesk = args.newsDesk;
      }
      if (args.normalizedByline !== undefined && args.normalizedByline !== null) {
        this.normalizedByline = args.normalizedByline;
      }
      if (args.onlineDescriptorList !== undefined && args.onlineDescriptorList !== null) {
        this.onlineDescriptorList = Thrift.copyList(args.onlineDescriptorList, [null]);
      }
      if (args.onlineHeadline !== undefined && args.onlineHeadline !== null) {
        this.onlineHeadline = args.onlineHeadline;
      }
      if (args.onlineLeadParagraph !== undefined && args.onlineLeadParagraph !== null) {
        this.onlineLeadParagraph = args.onlineLeadParagraph;
      }
      if (args.onlineLocationList !== undefined && args.onlineLocationList !== null) {
        this.onlineLocationList = Thrift.copyList(args.onlineLocationList, [null]);
      }
      if (args.onlineOrganizationList !== undefined && args.onlineOrganizationList !== null) {
        this.onlineOrganizationList = Thrift.copyList(args.onlineOrganizationList, [null]);
      }
      if (args.onlinePeople !== undefined && args.onlinePeople !== null) {
        this.onlinePeople = Thrift.copyList(args.onlinePeople, [null]);
      }
      if (args.onlineSectionList !== undefined && args.onlineSectionList !== null) {
        this.onlineSectionList = Thrift.copyList(args.onlineSectionList, [null]);
      }
      if (args.onlineTitleList !== undefined && args.onlineTitleList !== null) {
        this.onlineTitleList = Thrift.copyList(args.onlineTitleList, [null]);
      }
      if (args.organizationList !== undefined && args.organizationList !== null) {
        this.organizationList = Thrift.copyList(args.organizationList, [null]);
      }
      if (args.page !== undefined && args.page !== null) {
        this.page = args.page;
      }
      if (args.peopleList !== undefined && args.peopleList !== null) {
        this.peopleList = Thrift.copyList(args.peopleList, [null]);
      }
      if (args.publicationDate !== undefined && args.publicationDate !== null) {
        this.publicationDate = args.publicationDate;
      }
      if (args.publicationDayOfMonth !== undefined && args.publicationDayOfMonth !== null) {
        this.publicationDayOfMonth = args.publicationDayOfMonth;
      }
      if (args.publicationMonth !== undefined && args.publicationMonth !== null) {
        this.publicationMonth = args.publicationMonth;
      }
      if (args.publicationYear !== undefined && args.publicationYear !== null) {
        this.publicationYear = args.publicationYear;
      }
      if (args.section !== undefined && args.section !== null) {
        this.section = args.section;
      }
      if (args.seriesName !== undefined && args.seriesName !== null) {
        this.seriesName = args.seriesName;
      }
      if (args.slug !== undefined && args.slug !== null) {
        this.slug = args.slug;
      }
      if (args.taxonomicClassifierList !== undefined && args.taxonomicClassifierList !== null) {
        this.taxonomicClassifierList = Thrift.copyList(args.taxonomicClassifierList, [null]);
      }
      if (args.titleList !== undefined && args.titleList !== null) {
        this.titleList = Thrift.copyList(args.titleList, [null]);
      }
      if (args.typesOfMaterialList !== undefined && args.typesOfMaterialList !== null) {
        this.typesOfMaterialList = Thrift.copyList(args.typesOfMaterialList, [null]);
      }
      if (args.url !== undefined && args.url !== null) {
        this.url = args.url;
      }
      if (args.wordCount !== undefined && args.wordCount !== null) {
        this.wordCount = args.wordCount;
      }
    }
  }

  read (input) {
    input.readStructBegin();
    while (true) {
      const ret = input.readFieldBegin();
      const ftype = ret.ftype;
      const fid = ret.fid;
      if (ftype == Thrift.Type.STOP) {
        break;
      }
      switch (fid) {
        case 1:
        if (ftype == Thrift.Type.STRING) {
          this.alternateURL = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 2:
        if (ftype == Thrift.Type.STRING) {
          this.articleAbstract = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 3:
        if (ftype == Thrift.Type.STRING) {
          this.authorBiography = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 4:
        if (ftype == Thrift.Type.STRING) {
          this.banner = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 5:
        if (ftype == Thrift.Type.LIST) {
          this.biographicalCategoryList = [];
          const _rtmp31 = input.readListBegin();
          const _size0 = _rtmp31.size || 0;
          for (let _i2 = 0; _i2 < _size0; ++_i2) {
            let elem3 = null;
            elem3 = input.readString();
            this.biographicalCategoryList.push(elem3);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 6:
        if (ftype == Thrift.Type.STRING) {
          this.columnName = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 7:
        if (ftype == Thrift.Type.I32) {
          this.columnNumber = input.readI32();
        } else {
          input.skip(ftype);
        }
        break;
        case 8:
        if (ftype == Thrift.Type.I64) {
          this.correctionDate = input.readI64();
        } else {
          input.skip(ftype);
        }
        break;
        case 9:
        if (ftype == Thrift.Type.STRING) {
          this.correctionText = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 10:
        if (ftype == Thrift.Type.STRING) {
          this.credit = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 11:
        if (ftype == Thrift.Type.STRING) {
          this.dayOfWeek = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 12:
        if (ftype == Thrift.Type.LIST) {
          this.descriptorList = [];
          const _rtmp35 = input.readListBegin();
          const _size4 = _rtmp35.size || 0;
          for (let _i6 = 0; _i6 < _size4; ++_i6) {
            let elem7 = null;
            elem7 = input.readString();
            this.descriptorList.push(elem7);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 13:
        if (ftype == Thrift.Type.STRING) {
          this.featurePage = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 14:
        if (ftype == Thrift.Type.LIST) {
          this.generalOnlineDescriptorList = [];
          const _rtmp39 = input.readListBegin();
          const _size8 = _rtmp39.size || 0;
          for (let _i10 = 0; _i10 < _size8; ++_i10) {
            let elem11 = null;
            elem11 = input.readString();
            this.generalOnlineDescriptorList.push(elem11);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 15:
        if (ftype == Thrift.Type.I32) {
          this.guid = input.readI32();
        } else {
          input.skip(ftype);
        }
        break;
        case 16:
        if (ftype == Thrift.Type.STRING) {
          this.kicker = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 17:
        if (ftype == Thrift.Type.LIST) {
          this.leadParagraphList = [];
          const _rtmp313 = input.readListBegin();
          const _size12 = _rtmp313.size || 0;
          for (let _i14 = 0; _i14 < _size12; ++_i14) {
            let elem15 = null;
            elem15 = input.readString();
            this.leadParagraphList.push(elem15);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 18:
        if (ftype == Thrift.Type.LIST) {
          this.locationList = [];
          const _rtmp317 = input.readListBegin();
          const _size16 = _rtmp317.size || 0;
          for (let _i18 = 0; _i18 < _size16; ++_i18) {
            let elem19 = null;
            elem19 = input.readString();
            this.locationList.push(elem19);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 19:
        if (ftype == Thrift.Type.LIST) {
          this.nameList = [];
          const _rtmp321 = input.readListBegin();
          const _size20 = _rtmp321.size || 0;
          for (let _i22 = 0; _i22 < _size20; ++_i22) {
            let elem23 = null;
            elem23 = input.readString();
            this.nameList.push(elem23);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 20:
        if (ftype == Thrift.Type.STRING) {
          this.newsDesk = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 21:
        if (ftype == Thrift.Type.STRING) {
          this.normalizedByline = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 22:
        if (ftype == Thrift.Type.LIST) {
          this.onlineDescriptorList = [];
          const _rtmp325 = input.readListBegin();
          const _size24 = _rtmp325.size || 0;
          for (let _i26 = 0; _i26 < _size24; ++_i26) {
            let elem27 = null;
            elem27 = input.readString();
            this.onlineDescriptorList.push(elem27);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 23:
        if (ftype == Thrift.Type.STRING) {
          this.onlineHeadline = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 24:
        if (ftype == Thrift.Type.STRING) {
          this.onlineLeadParagraph = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 25:
        if (ftype == Thrift.Type.LIST) {
          this.onlineLocationList = [];
          const _rtmp329 = input.readListBegin();
          const _size28 = _rtmp329.size || 0;
          for (let _i30 = 0; _i30 < _size28; ++_i30) {
            let elem31 = null;
            elem31 = input.readString();
            this.onlineLocationList.push(elem31);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 26:
        if (ftype == Thrift.Type.LIST) {
          this.onlineOrganizationList = [];
          const _rtmp333 = input.readListBegin();
          const _size32 = _rtmp333.size || 0;
          for (let _i34 = 0; _i34 < _size32; ++_i34) {
            let elem35 = null;
            elem35 = input.readString();
            this.onlineOrganizationList.push(elem35);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 27:
        if (ftype == Thrift.Type.LIST) {
          this.onlinePeople = [];
          const _rtmp337 = input.readListBegin();
          const _size36 = _rtmp337.size || 0;
          for (let _i38 = 0; _i38 < _size36; ++_i38) {
            let elem39 = null;
            elem39 = input.readString();
            this.onlinePeople.push(elem39);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 28:
        if (ftype == Thrift.Type.LIST) {
          this.onlineSectionList = [];
          const _rtmp341 = input.readListBegin();
          const _size40 = _rtmp341.size || 0;
          for (let _i42 = 0; _i42 < _size40; ++_i42) {
            let elem43 = null;
            elem43 = input.readString();
            this.onlineSectionList.push(elem43);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 29:
        if (ftype == Thrift.Type.LIST) {
          this.onlineTitleList = [];
          const _rtmp345 = input.readListBegin();
          const _size44 = _rtmp345.size || 0;
          for (let _i46 = 0; _i46 < _size44; ++_i46) {
            let elem47 = null;
            elem47 = input.readString();
            this.onlineTitleList.push(elem47);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 30:
        if (ftype == Thrift.Type.LIST) {
          this.organizationList = [];
          const _rtmp349 = input.readListBegin();
          const _size48 = _rtmp349.size || 0;
          for (let _i50 = 0; _i50 < _size48; ++_i50) {
            let elem51 = null;
            elem51 = input.readString();
            this.organizationList.push(elem51);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 31:
        if (ftype == Thrift.Type.I32) {
          this.page = input.readI32();
        } else {
          input.skip(ftype);
        }
        break;
        case 32:
        if (ftype == Thrift.Type.LIST) {
          this.peopleList = [];
          const _rtmp353 = input.readListBegin();
          const _size52 = _rtmp353.size || 0;
          for (let _i54 = 0; _i54 < _size52; ++_i54) {
            let elem55 = null;
            elem55 = input.readString();
            this.peopleList.push(elem55);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 33:
        if (ftype == Thrift.Type.I64) {
          this.publicationDate = input.readI64();
        } else {
          input.skip(ftype);
        }
        break;
        case 34:
        if (ftype == Thrift.Type.I32) {
          this.publicationDayOfMonth = input.readI32();
        } else {
          input.skip(ftype);
        }
        break;
        case 35:
        if (ftype == Thrift.Type.I32) {
          this.publicationMonth = input.readI32();
        } else {
          input.skip(ftype);
        }
        break;
        case 36:
        if (ftype == Thrift.Type.I32) {
          this.publicationYear = input.readI32();
        } else {
          input.skip(ftype);
        }
        break;
        case 37:
        if (ftype == Thrift.Type.STRING) {
          this.section = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 38:
        if (ftype == Thrift.Type.STRING) {
          this.seriesName = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 39:
        if (ftype == Thrift.Type.STRING) {
          this.slug = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 40:
        if (ftype == Thrift.Type.LIST) {
          this.taxonomicClassifierList = [];
          const _rtmp357 = input.readListBegin();
          const _size56 = _rtmp357.size || 0;
          for (let _i58 = 0; _i58 < _size56; ++_i58) {
            let elem59 = null;
            elem59 = input.readString();
            this.taxonomicClassifierList.push(elem59);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 41:
        if (ftype == Thrift.Type.LIST) {
          this.titleList = [];
          const _rtmp361 = input.readListBegin();
          const _size60 = _rtmp361.size || 0;
          for (let _i62 = 0; _i62 < _size60; ++_i62) {
            let elem63 = null;
            elem63 = input.readString();
            this.titleList.push(elem63);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 42:
        if (ftype == Thrift.Type.LIST) {
          this.typesOfMaterialList = [];
          const _rtmp365 = input.readListBegin();
          const _size64 = _rtmp365.size || 0;
          for (let _i66 = 0; _i66 < _size64; ++_i66) {
            let elem67 = null;
            elem67 = input.readString();
            this.typesOfMaterialList.push(elem67);
          }
          input.readListEnd();
        } else {
          input.skip(ftype);
        }
        break;
        case 43:
        if (ftype == Thrift.Type.STRING) {
          this.url = input.readString();
        } else {
          input.skip(ftype);
        }
        break;
        case 44:
        if (ftype == Thrift.Type.I32) {
          this.wordCount = input.readI32();
        } else {
          input.skip(ftype);
        }
        break;
        default:
          input.skip(ftype);
      }
      input.readFieldEnd();
    }
    input.readStructEnd();
    return;
  }

  write (output) {
    output.writeStructBegin('NITFInfo');
    if (this.alternateURL !== null && this.alternateURL !== undefined) {
      output.writeFieldBegin('alternateURL', Thrift.Type.STRING, 1);
      output.writeString(this.alternateURL);
      output.writeFieldEnd();
    }
    if (this.articleAbstract !== null && this.articleAbstract !== undefined) {
      output.writeFieldBegin('articleAbstract', Thrift.Type.STRING, 2);
      output.writeString(this.articleAbstract);
      output.writeFieldEnd();
    }
    if (this.authorBiography !== null && this.authorBiography !== undefined) {
      output.writeFieldBegin('authorBiography', Thrift.Type.STRING, 3);
      output.writeString(this.authorBiography);
      output.writeFieldEnd();
    }
    if (this.banner !== null && this.banner !== undefined) {
      output.writeFieldBegin('banner', Thrift.Type.STRING, 4);
      output.writeString(this.banner);
      output.writeFieldEnd();
    }
    if (this.biographicalCategoryList !== null && this.biographicalCategoryList !== undefined) {
      output.writeFieldBegin('biographicalCategoryList', Thrift.Type.LIST, 5);
      output.writeListBegin(Thrift.Type.STRING, this.biographicalCategoryList.length);
      for (let iter68 in this.biographicalCategoryList) {
        if (this.biographicalCategoryList.hasOwnProperty(iter68)) {
          iter68 = this.biographicalCategoryList[iter68];
          output.writeString(iter68);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.columnName !== null && this.columnName !== undefined) {
      output.writeFieldBegin('columnName', Thrift.Type.STRING, 6);
      output.writeString(this.columnName);
      output.writeFieldEnd();
    }
    if (this.columnNumber !== null && this.columnNumber !== undefined) {
      output.writeFieldBegin('columnNumber', Thrift.Type.I32, 7);
      output.writeI32(this.columnNumber);
      output.writeFieldEnd();
    }
    if (this.correctionDate !== null && this.correctionDate !== undefined) {
      output.writeFieldBegin('correctionDate', Thrift.Type.I64, 8);
      output.writeI64(this.correctionDate);
      output.writeFieldEnd();
    }
    if (this.correctionText !== null && this.correctionText !== undefined) {
      output.writeFieldBegin('correctionText', Thrift.Type.STRING, 9);
      output.writeString(this.correctionText);
      output.writeFieldEnd();
    }
    if (this.credit !== null && this.credit !== undefined) {
      output.writeFieldBegin('credit', Thrift.Type.STRING, 10);
      output.writeString(this.credit);
      output.writeFieldEnd();
    }
    if (this.dayOfWeek !== null && this.dayOfWeek !== undefined) {
      output.writeFieldBegin('dayOfWeek', Thrift.Type.STRING, 11);
      output.writeString(this.dayOfWeek);
      output.writeFieldEnd();
    }
    if (this.descriptorList !== null && this.descriptorList !== undefined) {
      output.writeFieldBegin('descriptorList', Thrift.Type.LIST, 12);
      output.writeListBegin(Thrift.Type.STRING, this.descriptorList.length);
      for (let iter69 in this.descriptorList) {
        if (this.descriptorList.hasOwnProperty(iter69)) {
          iter69 = this.descriptorList[iter69];
          output.writeString(iter69);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.featurePage !== null && this.featurePage !== undefined) {
      output.writeFieldBegin('featurePage', Thrift.Type.STRING, 13);
      output.writeString(this.featurePage);
      output.writeFieldEnd();
    }
    if (this.generalOnlineDescriptorList !== null && this.generalOnlineDescriptorList !== undefined) {
      output.writeFieldBegin('generalOnlineDescriptorList', Thrift.Type.LIST, 14);
      output.writeListBegin(Thrift.Type.STRING, this.generalOnlineDescriptorList.length);
      for (let iter70 in this.generalOnlineDescriptorList) {
        if (this.generalOnlineDescriptorList.hasOwnProperty(iter70)) {
          iter70 = this.generalOnlineDescriptorList[iter70];
          output.writeString(iter70);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.guid !== null && this.guid !== undefined) {
      output.writeFieldBegin('guid', Thrift.Type.I32, 15);
      output.writeI32(this.guid);
      output.writeFieldEnd();
    }
    if (this.kicker !== null && this.kicker !== undefined) {
      output.writeFieldBegin('kicker', Thrift.Type.STRING, 16);
      output.writeString(this.kicker);
      output.writeFieldEnd();
    }
    if (this.leadParagraphList !== null && this.leadParagraphList !== undefined) {
      output.writeFieldBegin('leadParagraphList', Thrift.Type.LIST, 17);
      output.writeListBegin(Thrift.Type.STRING, this.leadParagraphList.length);
      for (let iter71 in this.leadParagraphList) {
        if (this.leadParagraphList.hasOwnProperty(iter71)) {
          iter71 = this.leadParagraphList[iter71];
          output.writeString(iter71);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.locationList !== null && this.locationList !== undefined) {
      output.writeFieldBegin('locationList', Thrift.Type.LIST, 18);
      output.writeListBegin(Thrift.Type.STRING, this.locationList.length);
      for (let iter72 in this.locationList) {
        if (this.locationList.hasOwnProperty(iter72)) {
          iter72 = this.locationList[iter72];
          output.writeString(iter72);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.nameList !== null && this.nameList !== undefined) {
      output.writeFieldBegin('nameList', Thrift.Type.LIST, 19);
      output.writeListBegin(Thrift.Type.STRING, this.nameList.length);
      for (let iter73 in this.nameList) {
        if (this.nameList.hasOwnProperty(iter73)) {
          iter73 = this.nameList[iter73];
          output.writeString(iter73);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.newsDesk !== null && this.newsDesk !== undefined) {
      output.writeFieldBegin('newsDesk', Thrift.Type.STRING, 20);
      output.writeString(this.newsDesk);
      output.writeFieldEnd();
    }
    if (this.normalizedByline !== null && this.normalizedByline !== undefined) {
      output.writeFieldBegin('normalizedByline', Thrift.Type.STRING, 21);
      output.writeString(this.normalizedByline);
      output.writeFieldEnd();
    }
    if (this.onlineDescriptorList !== null && this.onlineDescriptorList !== undefined) {
      output.writeFieldBegin('onlineDescriptorList', Thrift.Type.LIST, 22);
      output.writeListBegin(Thrift.Type.STRING, this.onlineDescriptorList.length);
      for (let iter74 in this.onlineDescriptorList) {
        if (this.onlineDescriptorList.hasOwnProperty(iter74)) {
          iter74 = this.onlineDescriptorList[iter74];
          output.writeString(iter74);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.onlineHeadline !== null && this.onlineHeadline !== undefined) {
      output.writeFieldBegin('onlineHeadline', Thrift.Type.STRING, 23);
      output.writeString(this.onlineHeadline);
      output.writeFieldEnd();
    }
    if (this.onlineLeadParagraph !== null && this.onlineLeadParagraph !== undefined) {
      output.writeFieldBegin('onlineLeadParagraph', Thrift.Type.STRING, 24);
      output.writeString(this.onlineLeadParagraph);
      output.writeFieldEnd();
    }
    if (this.onlineLocationList !== null && this.onlineLocationList !== undefined) {
      output.writeFieldBegin('onlineLocationList', Thrift.Type.LIST, 25);
      output.writeListBegin(Thrift.Type.STRING, this.onlineLocationList.length);
      for (let iter75 in this.onlineLocationList) {
        if (this.onlineLocationList.hasOwnProperty(iter75)) {
          iter75 = this.onlineLocationList[iter75];
          output.writeString(iter75);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.onlineOrganizationList !== null && this.onlineOrganizationList !== undefined) {
      output.writeFieldBegin('onlineOrganizationList', Thrift.Type.LIST, 26);
      output.writeListBegin(Thrift.Type.STRING, this.onlineOrganizationList.length);
      for (let iter76 in this.onlineOrganizationList) {
        if (this.onlineOrganizationList.hasOwnProperty(iter76)) {
          iter76 = this.onlineOrganizationList[iter76];
          output.writeString(iter76);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.onlinePeople !== null && this.onlinePeople !== undefined) {
      output.writeFieldBegin('onlinePeople', Thrift.Type.LIST, 27);
      output.writeListBegin(Thrift.Type.STRING, this.onlinePeople.length);
      for (let iter77 in this.onlinePeople) {
        if (this.onlinePeople.hasOwnProperty(iter77)) {
          iter77 = this.onlinePeople[iter77];
          output.writeString(iter77);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.onlineSectionList !== null && this.onlineSectionList !== undefined) {
      output.writeFieldBegin('onlineSectionList', Thrift.Type.LIST, 28);
      output.writeListBegin(Thrift.Type.STRING, this.onlineSectionList.length);
      for (let iter78 in this.onlineSectionList) {
        if (this.onlineSectionList.hasOwnProperty(iter78)) {
          iter78 = this.onlineSectionList[iter78];
          output.writeString(iter78);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.onlineTitleList !== null && this.onlineTitleList !== undefined) {
      output.writeFieldBegin('onlineTitleList', Thrift.Type.LIST, 29);
      output.writeListBegin(Thrift.Type.STRING, this.onlineTitleList.length);
      for (let iter79 in this.onlineTitleList) {
        if (this.onlineTitleList.hasOwnProperty(iter79)) {
          iter79 = this.onlineTitleList[iter79];
          output.writeString(iter79);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.organizationList !== null && this.organizationList !== undefined) {
      output.writeFieldBegin('organizationList', Thrift.Type.LIST, 30);
      output.writeListBegin(Thrift.Type.STRING, this.organizationList.length);
      for (let iter80 in this.organizationList) {
        if (this.organizationList.hasOwnProperty(iter80)) {
          iter80 = this.organizationList[iter80];
          output.writeString(iter80);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.page !== null && this.page !== undefined) {
      output.writeFieldBegin('page', Thrift.Type.I32, 31);
      output.writeI32(this.page);
      output.writeFieldEnd();
    }
    if (this.peopleList !== null && this.peopleList !== undefined) {
      output.writeFieldBegin('peopleList', Thrift.Type.LIST, 32);
      output.writeListBegin(Thrift.Type.STRING, this.peopleList.length);
      for (let iter81 in this.peopleList) {
        if (this.peopleList.hasOwnProperty(iter81)) {
          iter81 = this.peopleList[iter81];
          output.writeString(iter81);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.publicationDate !== null && this.publicationDate !== undefined) {
      output.writeFieldBegin('publicationDate', Thrift.Type.I64, 33);
      output.writeI64(this.publicationDate);
      output.writeFieldEnd();
    }
    if (this.publicationDayOfMonth !== null && this.publicationDayOfMonth !== undefined) {
      output.writeFieldBegin('publicationDayOfMonth', Thrift.Type.I32, 34);
      output.writeI32(this.publicationDayOfMonth);
      output.writeFieldEnd();
    }
    if (this.publicationMonth !== null && this.publicationMonth !== undefined) {
      output.writeFieldBegin('publicationMonth', Thrift.Type.I32, 35);
      output.writeI32(this.publicationMonth);
      output.writeFieldEnd();
    }
    if (this.publicationYear !== null && this.publicationYear !== undefined) {
      output.writeFieldBegin('publicationYear', Thrift.Type.I32, 36);
      output.writeI32(this.publicationYear);
      output.writeFieldEnd();
    }
    if (this.section !== null && this.section !== undefined) {
      output.writeFieldBegin('section', Thrift.Type.STRING, 37);
      output.writeString(this.section);
      output.writeFieldEnd();
    }
    if (this.seriesName !== null && this.seriesName !== undefined) {
      output.writeFieldBegin('seriesName', Thrift.Type.STRING, 38);
      output.writeString(this.seriesName);
      output.writeFieldEnd();
    }
    if (this.slug !== null && this.slug !== undefined) {
      output.writeFieldBegin('slug', Thrift.Type.STRING, 39);
      output.writeString(this.slug);
      output.writeFieldEnd();
    }
    if (this.taxonomicClassifierList !== null && this.taxonomicClassifierList !== undefined) {
      output.writeFieldBegin('taxonomicClassifierList', Thrift.Type.LIST, 40);
      output.writeListBegin(Thrift.Type.STRING, this.taxonomicClassifierList.length);
      for (let iter82 in this.taxonomicClassifierList) {
        if (this.taxonomicClassifierList.hasOwnProperty(iter82)) {
          iter82 = this.taxonomicClassifierList[iter82];
          output.writeString(iter82);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.titleList !== null && this.titleList !== undefined) {
      output.writeFieldBegin('titleList', Thrift.Type.LIST, 41);
      output.writeListBegin(Thrift.Type.STRING, this.titleList.length);
      for (let iter83 in this.titleList) {
        if (this.titleList.hasOwnProperty(iter83)) {
          iter83 = this.titleList[iter83];
          output.writeString(iter83);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.typesOfMaterialList !== null && this.typesOfMaterialList !== undefined) {
      output.writeFieldBegin('typesOfMaterialList', Thrift.Type.LIST, 42);
      output.writeListBegin(Thrift.Type.STRING, this.typesOfMaterialList.length);
      for (let iter84 in this.typesOfMaterialList) {
        if (this.typesOfMaterialList.hasOwnProperty(iter84)) {
          iter84 = this.typesOfMaterialList[iter84];
          output.writeString(iter84);
        }
      }
      output.writeListEnd();
      output.writeFieldEnd();
    }
    if (this.url !== null && this.url !== undefined) {
      output.writeFieldBegin('url', Thrift.Type.STRING, 43);
      output.writeString(this.url);
      output.writeFieldEnd();
    }
    if (this.wordCount !== null && this.wordCount !== undefined) {
      output.writeFieldBegin('wordCount', Thrift.Type.I32, 44);
      output.writeI32(this.wordCount);
      output.writeFieldEnd();
    }
    output.writeFieldStop();
    output.writeStructEnd();
    return;
  }

};
